"""empty message

Revision ID: 267446528764
Revises: 4accbe4294b0
Create Date: 2019-02-26 20:11:08.953529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267446528764'
down_revision = '4accbe4294b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_applications', sa.Column('is_awarded', sa.Boolean(), nullable=True))
    op.add_column('grant_applications', sa.Column('is_pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_applications', 'is_pending')
    op.drop_column('grant_applications', 'is_awarded')
    # ### end Alembic commands ###
