"""add funding call + attachment table

Revision ID: 4fa1dc738be2
Revises: 8f835e18fb0b
Create Date: 2019-01-29 10:22:39.091343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa1dc738be2'
down_revision = '8f835e18fb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('rolling', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('award_amount', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('blurb', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_call_timestamp'), 'funding_call', ['timestamp'], unique=False)
    op.create_table('funding_call_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['funding_call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_call_attachment')
    op.drop_index(op.f('ix_funding_call_timestamp'), table_name='funding_call')
    op.drop_table('funding_call')
    # ### end Alembic commands ###
