"""empty message

Revision ID: 73d6405ae407
Revises: 
Create Date: 2019-02-24 17:03:46.621408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d6405ae407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_applications', sa.Column('coapps', sa.Text(), nullable=True))
    op.add_column('grant_applications', sa.Column('collabs', sa.Text(), nullable=True))
    op.add_column('grant_applications', sa.Column('ethical_q1', sa.Text(), nullable=True))
    op.add_column('grant_applications', sa.Column('ethical_q2', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'grant_applications', 'funding_call', ['call_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grant_applications', type_='foreignkey')
    op.drop_column('grant_applications', 'ethical_q2')
    op.drop_column('grant_applications', 'ethical_q1')
    op.drop_column('grant_applications', 'collabs')
    op.drop_column('grant_applications', 'coapps')
    # ### end Alembic commands ###
