"""Adding 2 tables to query publications & events associated with grants

Revision ID: 7831bd8500ab
Revises: aef2db53c2bd
Create Date: 2019-02-28 20:58:19.211610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7831bd8500ab'
down_revision = 'aef2db53c2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_events',
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_row', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_row'], ['events.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('grant_id', 'user_id', 'event_row')
    )
    op.create_table('grant_publications',
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pub_row', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['pub_row'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('grant_id', 'user_id', 'pub_row')
    )
    op.add_column('collaborators', sa.Column('events', sa.Integer(), nullable=True))
    op.add_column('collaborators', sa.Column('publications', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collaborators', 'publication', ['publications'], ['id'])
    op.create_foreign_key(None, 'collaborators', 'events', ['events'], ['id'])
    op.create_foreign_key(None, 'reviews', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'user', ['username'], ['username'])
    op.create_foreign_key(None, 'reviews', 'grant_applications', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'grant_applications', ['proposal_title'], ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.drop_column('collaborators', 'publications')
    op.drop_column('collaborators', 'events')
    op.drop_table('grant_publications')
    op.drop_table('grant_events')
    # ### end Alembic commands ###
