"""empty message

Revision ID: 78ad6ad4053e
Revises: 
Create Date: 2019-02-21 04:41:34.968655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ad6ad4053e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_group_name'), 'research_group', ['name'], unique=False)
    op.create_table('grant_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('nrp', sa.Text(), nullable=True),
    sa.Column('legal_align', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('sci_abstract', sa.Text(), nullable=True),
    sa.Column('lay_abstract', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['research_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_user', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('doi', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['primary_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sfi_proposal_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('funding', sa.Text(), nullable=True),
    sa.Column('key_dates', sa.Text(), nullable=True),
    sa.Column('upload_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant_application_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grant_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('publications')
    op.add_column('user', sa.Column('is_reviewer', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('orcid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_orcid'), 'user', ['orcid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_orcid'), table_name='user')
    op.drop_column('user', 'orcid')
    op.drop_column('user', 'is_reviewer')
    op.create_table('publications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('grant_application_attachment')
    op.drop_table('sfi_proposal_calls')
    op.drop_table('publication')
    op.drop_table('group_membership')
    op.drop_table('grant_applications')
    op.drop_index(op.f('ix_research_group_name'), table_name='research_group')
    op.drop_table('research_group')
    # ### end Alembic commands ###
