"""general info table

Revision ID: 7916e3ec1dd7
Revises: ddcf69076328
Create Date: 2019-01-23 21:40:08.043149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7916e3ec1dd7'
down_revision = 'ddcf69076328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_general_information', sa.Column('phoneNum', sa.String(length=64), nullable=True))
    op.add_column('user_general_information', sa.Column('prefix', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_general_information', 'prefix')
    op.drop_column('user_general_information', 'phoneNum')
    # ### end Alembic commands ###
