"""adding annual report table

Revision ID: 91c8647ac1d3
Revises: a5706222b1d7
Create Date: 2019-02-21 20:14:59.113770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c8647ac1d3'
down_revision = 'a5706222b1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_submit', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('publications_data', sa.Text(), nullable=True),
    sa.Column('edu_pub_engagement', sa.Text(), nullable=True),
    sa.Column('academic_collab', sa.Text(), nullable=True),
    sa.Column('nonacademic_collab', sa.Text(), nullable=True),
    sa.Column('commerc', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('deviations', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual_report')
    # ### end Alembic commands ###
