"""Adding is_reviewer to Users

Revision ID: a5706222b1d7
Revises: acb2e8fe8636
Create Date: 2019-02-19 12:36:56.879777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5706222b1d7'
down_revision = 'acb2e8fe8636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_reviewer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_reviewer')
    # ### end Alembic commands ###
