"""Migrating grants and collaborators again

Revision ID: aef2db53c2bd
Revises: 46eb56be6a71
Create Date: 2019-02-27 15:02:17.156587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef2db53c2bd'
down_revision = '46eb56be6a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['grant_applications.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['funding_call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborators',
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_pi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('grant_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    op.drop_table('grants')
    # ### end Alembic commands ###
