"""empty message

Revision ID: d2db634a2676
Revises: b8218343158f
Create Date: 2019-02-07 23:48:31.107601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2db634a2676'
down_revision = 'b8218343158f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sfi_proposal_calls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sfi_proposal_calls', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sfi_proposal_calls', type_='foreignkey')
    op.drop_column('sfi_proposal_calls', 'user_id')
    # ### end Alembic commands ###
