"""empty message

Revision ID: d3070d56753c
Revises: 
Create Date: 2019-02-26 22:29:11.250844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3070d56753c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_submit', sa.Boolean(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('publications_data', sa.Text(), nullable=True),
    sa.Column('edu_pub_engagement', sa.Text(), nullable=True),
    sa.Column('academic_collab', sa.Text(), nullable=True),
    sa.Column('nonacademic_collab', sa.Text(), nullable=True),
    sa.Column('commerc', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('deviations', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_call_reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['funding_call.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['funding_call.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('grant_applications', 'is_pending')
    op.drop_column('grant_applications', 'is_draft')
    op.drop_column('grant_applications', 'is_awarded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_applications', sa.Column('is_awarded', sa.BOOLEAN(), nullable=True))
    op.add_column('grant_applications', sa.Column('is_draft', sa.BOOLEAN(), nullable=True))
    op.add_column('grant_applications', sa.Column('is_pending', sa.BOOLEAN(), nullable=True))
    op.drop_table('reviews')
    op.drop_table('funding_call_reviewers')
    op.drop_table('annual_report')
    # ### end Alembic commands ###
